nome = input('Insira o nome do vendedor: ')
salaro_fixo = float (input('Digite o salário fixo do vendedor: '))
total_vendas_sq = float (input('Digite o total de vendas, entre segunda e quarta-feira: R$ '))
total_vendas_qs = float (input('Digite o total de vendas, entre quinta e sexta-feira: R$ '))
total_vendas_sd = float (input('Digite o total de vendas, entre sábados e domingos: R$ '))
comissao1 = (total_vendas_sq * 0.20)
comissao2 = (total_vendas_qs * 0.15)
comissao3 = (total_vendas_sd * 0.10)
salaro_total = (salaro_fixo + comissao1 + comissao2 + comissao3 )
print (f'O salário total do vendedor no final do mês é de: R${salaro_total:.2f}')